###
POST http://localhost:5052/login
Content-Type: application/json

{
    "username": "Adam"
}

###
GET http://localhost:5050/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkYW0iLCJpYXQiOjE3ODg4MTU0OTYsImV4cCI6MTc4ODgxNTUxMX0.-ORLRA0_G_8QbJQ5B4XsoVWGnrLQbg6SQzvgsbA59G0

###
POST http://localhost:5052/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkYW0iLCJpYXQiOjE3ODg4MTU0Nzh9.C48rPb8FmaCDyPfj0aYp--FoKcwr_lH1C4KW46x493w"
}

